language: python
python:
  - '3.9'
script:
  - echo "Hello World"
deploy:
  provider: pypi
  username: "__token__"
  password: "$PYPI_TOKEN"
  on:
    branches:
      only:
        - master
        - travis